# Generated by Django 2.2.4 on 2022-02-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('confirm_pw', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploded', to='login_app.Login')),
                ('users_who_likes', models.ManyToManyField(related_name='liked_books', to='login_app.Login')),
            ],
        ),
        migrations.CreateModel(
            name='WhishGranted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_uploded', to='login_app.Login')),
                ('whish_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='whish_uploded', to='login_app.Whish')),
            ],
        ),
    ]
