# Generated by Django 2.2.4 on 2022-02-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20220226_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
    ]
