# Generated by Django 2.2.4 on 2022-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_movie_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uplode_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
